const FLAGS={"England":"🏴","Portugal":"🇵🇹","Brazil":"🇧🇷","Netherlands":"🇳🇱","Morocco":"🇲🇦","Belgium":"🇧🇪","Germany":"🇩🇪","Croatia":"🇭🇷","Colombia":"🇨🇴","Senegal":"🇸🇳","Mexico":"🇲🇽","United States":"🇺🇸","Uruguay":"🇺🇾","Japan":"🇯🇵","Switzerland":"🇨🇭","Iran":"🇮🇷","Türkiye":"🇹🇷","Turkey":"🇹🇷","Austria":"🇦🇹","Norway":"🇳🇴","Paraguay":"🇵🇾"};
function norm(name){if(!name)return"";const n=String(name).trim();const low=n.toLowerCase();if(["turkey","turkiye","türkiye"].includes(low))return"Türkiye";if(["usa","united states of america","usmnt"].includes(low))return"United States";return n}
function badge(team){const t=norm(team);return `<span class="badge">${FLAGS[t]||"⚽"} ${t}</span>`}
function teamScore(team,data){const t=norm(team);return data.teamStats?.[t]||{points:0,played:0,wins:0,draws:0,losses:0,bonus:0}}
function buildLeaderboard(config,data){return config.players.map(player=>{const stats=player.teams.map(t=>teamScore(t,data));return{name:player.name,teams:player.teams,points:stats.reduce((a,b)=>a+(b.points||0),0),played:stats.reduce((a,b)=>a+(b.played||0),0),wins:stats.reduce((a,b)=>a+(b.wins||0),0),draws:stats.reduce((a,b)=>a+(b.draws||0),0),losses:stats.reduce((a,b)=>a+(b.losses||0),0)}}).sort((a,b)=>b.points-a.points||b.wins-a.wins||a.name.localeCompare(b.name))}
function renderPodium(rows){document.getElementById("podium").innerHTML=rows.slice(0,3).map((r,i)=>`<div class="podium-card"><div class="medal">${["🥇","🥈","🥉"][i]}</div><div class="name">${r.name}</div><div class="badges">${r.teams.map(badge).join("")}</div><div class="points">${r.points} pts</div></div>`).join("")}
function renderLeaderboard(rows){document.getElementById("leaderboard").innerHTML=rows.map((r,i)=>`<tr><td class="rank">${i+1}</td><td><strong>${r.name}</strong></td><td><div class="badges">${r.teams.map(badge).join("")}</div></td><td class="points">${r.points}</td><td>${r.wins}W ${r.draws}D ${r.losses}L</td></tr>`).join("")}
function renderTeams(config,data){document.getElementById("teamGrid").innerHTML=config.players.map(player=>`<div class="team-card"><strong>${player.name}</strong><div class="badges">${player.teams.map(t=>{const s=teamScore(t,data);return `<span class="badge">${FLAGS[norm(t)]||"⚽"} ${norm(t)} — ${s.points||0} pts</span>`}).join("")}</div></div>`).join("")}
function renderMatches(config,data){const tracked=new Set(config.players.flatMap(p=>p.teams.map(norm)));const matches=(data.matches||[]).filter(m=>tracked.has(norm(m.homeTeam))||tracked.has(norm(m.awayTeam))).sort((a,b)=>new Date(b.utcDate||0)-new Date(a.utcDate||0)).slice(0,8);const el=document.getElementById("matches");if(!matches.length){el.innerHTML=`<p class="muted">No matches found yet. This will populate once the API has World Cup fixture/result data.</p>`;return}el.innerHTML=matches.map(m=>{const hs=m.homeScore??"-";const as=m.awayScore??"-";const when=m.utcDate?new Date(m.utcDate).toLocaleString([],{dateStyle:"medium",timeStyle:"short"}):"Date TBC";return `<div class="match-card"><div class="match-meta"><span>${when}</span><span>${m.status||"TBC"}</span></div><div>${badge(m.homeTeam)} <span class="score">${hs}</span> - <span class="score">${as}</span> ${badge(m.awayTeam)}</div></div>`}).join("")}
async function main(){const [config,data]=await Promise.all([fetch("config.json",{cache:"no-store"}).then(r=>r.json()),fetch("data.json",{cache:"no-store"}).then(r=>r.json()).catch(()=>({matches:[],teamStats:{},error:"No data.json yet"}))]);const status=document.getElementById("statusPill");const lastUpdated=document.getElementById("lastUpdated");if(data.error){status.textContent="Needs setup";status.classList.add("bad");lastUpdated.textContent=data.error}else{status.textContent="Live data ready";status.classList.remove("bad");lastUpdated.textContent=data.lastUpdated?`Updated ${new Date(data.lastUpdated).toLocaleString()}`:"Waiting for first update"}const rows=buildLeaderboard(config,data);renderPodium(rows);renderLeaderboard(rows);renderTeams(config,data);renderMatches(config,data)}main();