const fs = require("fs");
const token = process.env.FOOTBALL_DATA_TOKEN;
if (!token) throw new Error("Missing FOOTBALL_DATA_TOKEN secret");
const config = JSON.parse(fs.readFileSync("config.json", "utf8"));
const trackedTeams = new Set(config.players.flatMap(p => p.teams.map(normalise)));
function normalise(name){if(!name)return"";const n=String(name).trim();const low=n.toLowerCase();if(["turkey","turkiye","türkiye"].includes(low))return"Türkiye";if(["usa","united states of america"].includes(low))return"United States";return n}
async function fd(path){const res=await fetch(`https://api.football-data.org/v4${path}`,{headers:{"X-Auth-Token":token}});const text=await res.text();if(!res.ok)throw new Error(`${res.status} ${res.statusText}: ${text}`);return JSON.parse(text)}
function matchScore(score,side){if(!score)return null;const ft=score.fullTime||{};return side==="home"?ft.home:ft.away}
function stageBonus(stage,status,winnerName,teamName){const s=String(stage||"").toUpperCase();const st=String(status||"").toUpperCase();if(st==="FINISHED"&&winnerName&&normalise(winnerName)===normalise(teamName)&&s.includes("FINAL"))return config.scoring.winner;if(s.includes("FINAL"))return config.scoring.runnerUp;if(s.includes("SEMI"))return config.scoring.semiFinal;if(s.includes("QUARTER"))return config.scoring.quarterFinal;if(s.includes("LAST_16")||s.includes("ROUND_OF_16"))return config.scoring.roundOf16;if(s.includes("LAST_32")||s.includes("ROUND_OF_32"))return config.scoring.roundOf32;return 0}
async function main(){const competition=config.competitionCode||"WC";const matchesPayload=await fd(`/competitions/${competition}/matches`);const rawMatches=matchesPayload.matches||[];const teamStats={};for(const t of trackedTeams)teamStats[t]={points:0,played:0,wins:0,draws:0,losses:0,bonus:0};const matches=rawMatches.map(m=>{const homeTeam=normalise(m.homeTeam?.name||m.homeTeam?.shortName||"");const awayTeam=normalise(m.awayTeam?.name||m.awayTeam?.shortName||"");const homeScore=matchScore(m.score,"home");const awayScore=matchScore(m.score,"away");if(m.status==="FINISHED"&&homeTeam&&awayTeam&&homeScore!==null&&awayScore!==null){if(teamStats[homeTeam])teamStats[homeTeam].played+=1;if(teamStats[awayTeam])teamStats[awayTeam].played+=1;if(homeScore>awayScore){if(teamStats[homeTeam]){teamStats[homeTeam].points+=config.scoring.win;teamStats[homeTeam].wins+=1}if(teamStats[awayTeam])teamStats[awayTeam].losses+=1}else if(awayScore>homeScore){if(teamStats[awayTeam]){teamStats[awayTeam].points+=config.scoring.win;teamStats[awayTeam].wins+=1}if(teamStats[homeTeam])teamStats[homeTeam].losses+=1}else{if(teamStats[homeTeam]){teamStats[homeTeam].points+=config.scoring.draw;teamStats[homeTeam].draws+=1}if(teamStats[awayTeam]){teamStats[awayTeam].points+=config.scoring.draw;teamStats[awayTeam].draws+=1}}}const winnerName=m.score?.winner==="HOME_TEAM"?homeTeam:m.score?.winner==="AWAY_TEAM"?awayTeam:"";for(const team of[homeTeam,awayTeam])if(teamStats[team])teamStats[team].bonus=Math.max(teamStats[team].bonus,stageBonus(m.stage,m.status,winnerName,team));return{id:m.id,utcDate:m.utcDate,status:m.status,stage:m.stage,group:m.group,homeTeam,awayTeam,homeScore,awayScore}});for(const team of Object.keys(teamStats))teamStats[team].points+=teamStats[team].bonus;fs.writeFileSync("data.json",JSON.stringify({lastUpdated:new Date().toISOString(),source:"football-data.org",matches,teamStats,error:null},null,2))}
main().catch(err=>{const fallback={lastUpdated:new Date().toISOString(),source:"football-data.org",matches:[],teamStats:Object.fromEntries([...trackedTeams].map(t=>[t,{points:0,played:0,wins:0,draws:0,losses:0,bonus:0}])),error:`Updater failed: ${err.message}`};fs.writeFileSync("data.json",JSON.stringify(fallback,null,2));console.error(err);process.exit(1)});
